services:
    producer:
        build:
          context: .
          dockerfile: Dockerfile-producer.DockerFile
        container_name: producer
        networks:
            - weather_pipe
    consumer1:
        build:
            context: .
            dockerfile: Dockerfile-consumer-weather.DockerFile
        depends_on:
            - producer
        container_name: consumer_weather
        networks:
            - weather_pipe

    consumer2:
        build:
            context: .
            dockerfile: Dockerfile-consumer-location.DockerFile
        depends_on:
            - producer
        container_name: consumer_location
        networks:
            - weather_pipe


networks:
  weather_pipe:
    driver: bridge